name: Update AltStore/SideStore Source

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Poetry version
        run: poetry --version

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: auto-ci

      - name: Configure git
        run: |
          git config user.name "Fries_I23"
          git config user.email "20661034+FriesI23@users.noreply.github.com"

      - name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH_NAME: auto-ci
        run: |
          cd scripts/update_repo
          poetry install
          poetry run python update_repo.py -s ../../_site/repo/source.json
          cd ../..
          git add _site/repo/source.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update source on $(date +%Y-%m-%d)"
            git push origin $BRANCH_NAME
          else
            echo "No changes to commit"
          fi

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BASE_BRANCH_NAME: master
          BRANCH_NAME: auto-ci
        run: |
          git fetch origin $BASE_BRANCH_NAME
          if ! git diff --quiet origin/$BASE_BRANCH_NAME...$BRANCH_NAME; then
            EXISTING_PR=$(gh pr list --base "$BASE_BRANCH_NAME" --head "$BRANCH_NAME" --state open --json number --jq '.[0].number')

            PR_URL=$(gh pr create \
              --base "$BASE_BRANCH_NAME" \
              --head "$BRANCH_NAME" \
              --title "Auto Update source" \
              --body "Automated update source on $(date +%Y-%m-%d).")
            NEW_PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')

            if [ -n "$EXISTING_PR" ]; then
              gh pr comment "$EXISTING_PR" --body "Auto-closing in favor of #$NEW_PR_NUMBER."
              gh pr close "$EXISTING_PR"
            fi
          else
            echo "No changes detected. Skipping PR creation."
          fi
